{
 "title": "Dashboard_1",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Распределение по бакетам",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_metric_histogram_bucket{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Длительность запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "Длительность запросов к сервису"
    }
   ]
  },
  {
   "title": "Частота запросов",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{instance=\"score-model:8000\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя нагруженоость процессора",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[1m])) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5хх 4хх ответы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}